### ISSUE TITLE
Paket İsimleri Duzenleme

### ISSUE THREAD

**Issue by volsahin** [metalcoder/E-Commerce#1]

**Comment by volsahin** [comment]
done this morning

**Comment by msayan** [comment]
com.telpa.ecommerce içindeki UI paketinin isminin ui olarak değiştirilmesi gerekiyor. ayrıca içerisinde bulunan Fragments klasörünün ismi fragment olarak değiştirilip com.telpa.ecommerce dizinine taşınması gerekli.

**Comment by msayan** [comment]
TabHelper classı utils paketine taşınması gerekli.

**Comment by volsahin** [comment]
degistirildi tesekkurler
