### ISSUE TITLE
Activity H ve I geliştirilmesi

### ISSUE THREAD

**Issue by volsahin** [metalcoder/E-Commerce#12]

**Comment by gzmilgar** [comment]
Activity H ve I geliştirildi

**Comment by msayan** [comment]
activtiy h' de cardview recyclerview'e değiştirilecek
itemlardaki renkler düzenlenecek
alta gölge eklenecek

**Comment by msayan** [comment]
activity ı cardview recyclerview'e değiştirilecek
margin paddingler yazı boyutları düzenlenecek 
alta gölge eklenecek

**Comment by gzmilgar** [comment]
activity  ı ve activity h cardview recyclerview'e değiştirildi.
margin paddingler yazı boyutları düzenlendi
alta gölge eklendi
