### ISSUE TITLE
Category E Ekran Geliştirilmesi

### ISSUE THREAD

**Issue by volsahin** [metalcoder/E-Commerce#9]
Frame Layout kullan !

**Comment by musacibik** [comment]
Done! (with Volkan)

**Comment by msayan** [comment]
resim değiştirilmesi
marginler düzenlenecek
itemdaki sol alttaki kayan yazı düzenlenecek

**Comment by volsahin** [comment]
yeniden düzenlendi

**Comment by msayan** [comment]
padding düzenlenecek, resim ortalanacak

**Comment by musacibik** [comment]
Yapıldı
